---
# ============================================================================
# Drone CI/CD Pipeline Configuration
# ============================================================================
# 
# 配置文件按功能模块组织：
#   1. Build Pipelines    - 构建步骤（demo, prod 环境的镜像构建）
#   2. Test Pipeline     - 测试环境完整流程（构建 + 部署）
#   3. Deploy Pipelines  - 部署步骤（demo, prod 环境的部署）
#   4. Secret Definitions - 所有 Secrets 定义
#
# ----------------------------------------------------------------------------
# Production Environment - Build Pipeline
# ----------------------------------------------------------------------------
kind: pipeline
type: kubernetes
name: prod-build-roma

trigger:
  event:
    - tag

steps:
  - name: build backend image
    image: plugins/docker
    settings:
      dockerfile: deployment/Dockerfile.ali
      context: .
      repo: registry.cn-hongkong.aliyuncs.com/binrchq/roma
      registry: registry.cn-hongkong.aliyuncs.com
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - ${DRONE_TAG}
        - latest

---
kind: pipeline
type: kubernetes
name: prod-deploy-roma

trigger:
  event:
    - tag

depends_on:
  - prod-build-roma

steps:
  - name: create production secrets
    image: registry.cn-hongkong.aliyuncs.com/binrcbase/kubectl
    environment:
      KUBECONFIG:
        from_secret: kubeconfig_data
      ROMA_APIKEY_KEY:
        from_secret: PROD_roma-apikey-key
      ROMA_USER_1ST_EMAIL:
        from_secret: PROD_roma-user-1st-email
      ROMA_USER_1ST_PASSWORD:
        from_secret: PROD_roma-user-1st-password
      ROMA_USER_1ST_USERNAME:
        from_secret: PROD_roma-user-1st-username
      ROMA_USER_1ST_PUBLIC_KEY:
        from_secret: PROD_roma-user-1st-public-key
      ROMA_CONTROL_PASSPORT_PASSPORT:
        from_secret: PROD_roma-control-passport-passport
      ROMA_CONTROL_PASSPORT_PASSPORT_PUB:
        from_secret: PROD_roma-control-passport-passport-pub
      ROMA_CONTROL_PASSPORT_PASSWORD:
        from_secret: PROD_roma-control-passport-password
      ROMA_DATABASE_CDB_URL:
        from_secret: PROD_roma-database-cdb-url
      ROMA_USER_1ST_NAME:
        from_secret: PROD_roma-user-1st-name
      ROMA_USER_1ST_NICKNAME:
        from_secret: PROD_roma-user-1st-nickname
      ROMA_USER_1ST_ROLES:
        from_secret: PROD_roma-user-1st-roles
      ROMA_ENCRYPTION_KEY:
        from_secret: PROD_roma-encryption-key
      ROMA_JWT_SECRET:
        from_secret: PROD_roma-jwt-secret
      HOME: /root
    commands:
      - echo "$KUBECONFIG" > /drone/src/kubeconfig
      - echo "You can call the secrets like this examples below."
      - echo "ROMA_APIKEY_KEY $ROMA_APIKEY_KEY"
      - echo "ROMA_USER_1ST_EMAIL $ROMA_USER_1ST_EMAIL"
      - echo "ROMA_USER_1ST_PASSWORD $ROMA_USER_1ST_PASSWORD"
      - echo "ROMA_USER_1ST_USERNAME $ROMA_USER_1ST_USERNAME"
      - echo "ROMA_USER_1ST_PUBLIC_KEY $ROMA_USER_1ST_PUBLIC_KEY"
      - echo "ROMA_CONTROL_PASSPORT_PASSPORT $ROMA_CONTROL_PASSPORT_PASSPORT"
      - echo "ROMA_CONTROL_PASSPORT_PASSPORT_PUB $ROMA_CONTROL_PASSPORT_PASSPORT_PUB"
      - echo "ROMA_CONTROL_PASSPORT_PASSWORD $ROMA_CONTROL_PASSPORT_PASSWORD"
      - echo "ROMA_DATABASE_CDB_URL $ROMA_DATABASE_CDB_URL"
      - echo "ROMA_USER_1ST_NAME $ROMA_USER_1ST_NAME"
      - echo "ROMA_USER_1ST_NICKNAME $ROMA_USER_1ST_NICKNAME"
      - echo "ROMA_USER_1ST_ROLES $ROMA_USER_1ST_ROLES"
      - echo "ROMA_ENCRYPTION_KEY $ROMA_ENCRYPTION_KEY"
      - echo "ROMA_JWT_SECRET $ROMA_JWT_SECRET"
      - |
        set -e
        kubectl --kubeconfig=/drone/src/kubeconfig create secret generic roma-secrets \
          --from-literal=ROMA_APIKEY_KEY="$ROMA_APIKEY_KEY" \
          --from-literal=ROMA_USER_1ST_EMAIL="$ROMA_USER_1ST_EMAIL" \
          --from-literal=ROMA_USER_1ST_PASSWORD="$ROMA_USER_1ST_PASSWORD" \
          --from-literal=ROMA_USER_1ST_USERNAME="$ROMA_USER_1ST_USERNAME" \
          --from-literal=ROMA_USER_1ST_PUBLIC_KEY="$ROMA_USER_1ST_PUBLIC_KEY" \
          --from-literal=ROMA_CONTROL_PASSPORT_PASSPORT="$ROMA_CONTROL_PASSPORT_PASSPORT" \
          --from-literal=ROMA_CONTROL_PASSPORT_PASSPORT_PUB="$ROMA_CONTROL_PASSPORT_PASSPORT_PUB" \
          --from-literal=ROMA_CONTROL_PASSPORT_PASSWORD="$ROMA_CONTROL_PASSPORT_PASSWORD" \
          --from-literal=ROMA_DATABASE_CDB_URL="$ROMA_DATABASE_CDB_URL" \
          --from-literal=ROMA_USER_1ST_NAME="$ROMA_USER_1ST_NAME" \
          --from-literal=ROMA_USER_1ST_NICKNAME="$ROMA_USER_1ST_NICKNAME" \
          --from-literal=ROMA_USER_1ST_ROLES="$ROMA_USER_1ST_ROLES" \
          --from-literal=ROMA_ENCRYPTION_KEY="$ROMA_ENCRYPTION_KEY" \
          --from-literal=ROMA_JWT_SECRET="$ROMA_JWT_SECRET" \
          -n roma --dry-run=client -o yaml | kubectl --kubeconfig=/drone/src/kubeconfig apply -f -

  - name: deploy to prod
    image: registry.cn-hongkong.aliyuncs.com/binrcbase/kubectl
    environment:
      KUBECONFIG:
        from_secret: kubeconfig_data
      HOME: /root
      IMAGE_TAG: ${DRONE_TAG}
      NAMESPACE: roma
    commands:
      - echo "$KUBECONFIG" > /drone/src/kubeconfig
      - |
        sed -e "s|registry.cn-hongkong.aliyuncs.com/binrchq/roma:latest|registry.cn-hongkong.aliyuncs.com/binrchq/roma:$IMAGE_TAG|g" \
            deployment/k8s-deployment.yaml > /drone/src/k8s-deployment.deploy.yaml
      - kubectl --kubeconfig=/drone/src/kubeconfig apply -f /drone/src/k8s-deployment.deploy.yaml
      - kubectl --kubeconfig=/drone/src/kubeconfig rollout status deployment/roma-backend -n $NAMESPACE --timeout=5m

---
kind: pipeline
type: kubernetes
name: prod-deploy-roma-demo

trigger:
  event:
    - tag

depends_on:
  - prod-build-roma

steps:
  - name: create demo secrets
    image: registry.cn-hongkong.aliyuncs.com/binrcbase/kubectl
    environment:
      ROMA_APIKEY_KEY:
        from_secret: DEMO_roma-apikey-key
      ROMA_USER_1ST_EMAIL:
        from_secret: DEMO_roma-user-1st-email
      ROMA_USER_1ST_PASSWORD:
        from_secret: DEMO_roma-user-1st-password
      ROMA_USER_1ST_USERNAME:
        from_secret: DEMO_roma-user-1st-username
      ROMA_USER_1ST_PUBLIC_KEY:
        from_secret: DEMO_roma-user-1st-public-key
      ROMA_CONTROL_PASSPORT_PASSPORT:
        from_secret: DEMO_roma-control-passport-passport
      ROMA_CONTROL_PASSPORT_PASSPORT_PUB:
        from_secret: DEMO_roma-control-passport-passport-pub
      ROMA_CONTROL_PASSPORT_PASSWORD:
        from_secret: DEMO_roma-control-passport-password
      ROMA_DATABASE_CDB_URL:
        from_secret: DEMO_roma-database-cdb-url
      ROMA_USER_1ST_NAME:
        from_secret: DEMO_roma-user-1st-name
      ROMA_USER_1ST_NICKNAME:
        from_secret: DEMO_roma-user-1st-nickname
      ROMA_USER_1ST_ROLES:
        from_secret: DEMO_roma-user-1st-roles
      ROMA_ENCRYPTION_KEY:
        from_secret: DEMO_roma-encryption-key
      ROMA_JWT_SECRET:
        from_secret: DEMO_roma-jwt-secret
      KUBECONFIG:
        from_secret: KUBECONFIG_DATA
      HOME: /root
    commands:
      - echo "$KUBECONFIG" > /drone/src/kubeconfig
      - echo "You can call the secrets like this examples below."
      - echo "ROMA_APIKEY_KEY $ROMA_APIKEY_KEY"
      - echo "ROMA_USER_1ST_EMAIL $ROMA_USER_1ST_EMAIL"
      - echo "ROMA_USER_1ST_PASSWORD $ROMA_USER_1ST_PASSWORD"
      - echo "ROMA_USER_1ST_USERNAME $ROMA_USER_1ST_USERNAME"
      - echo "ROMA_USER_1ST_PUBLIC_KEY $ROMA_USER_1ST_PUBLIC_KEY"
      - echo "ROMA_CONTROL_PASSPORT_PASSPORT $ROMA_CONTROL_PASSPORT_PASSPORT"
      - echo "ROMA_CONTROL_PASSPORT_PASSPORT_PUB $ROMA_CONTROL_PASSPORT_PASSPORT_PUB"
      - echo "ROMA_CONTROL_PASSPORT_PASSWORD $ROMA_CONTROL_PASSPORT_PASSWORD"
      - echo "ROMA_DATABASE_CDB_URL $ROMA_DATABASE_CDB_URL"    
      - echo "ROMA_USER_1ST_NAME $ROMA_USER_1ST_NAME"
      - echo "ROMA_USER_1ST_NICKNAME $ROMA_USER_1ST_NICKNAME"
      - echo "ROMA_USER_1ST_ROLES $ROMA_USER_1ST_ROLES"
      - echo "ROMA_ENCRYPTION_KEY $ROMA_ENCRYPTION_KEY"
      - echo "ROMA_JWT_SECRET $ROMA_JWT_SECRET"
      - |
        set -e
        kubectl --kubeconfig=/drone/src/kubeconfig create secret generic roma-secrets \
          --from-literal=ROMA_APIKEY_KEY="$ROMA_APIKEY_KEY" \
          --from-literal=ROMA_USER_1ST_EMAIL="$ROMA_USER_1ST_EMAIL" \
          --from-literal=ROMA_USER_1ST_PASSWORD="$ROMA_USER_1ST_PASSWORD" \
          --from-literal=ROMA_USER_1ST_USERNAME="$ROMA_USER_1ST_USERNAME" \
          --from-literal=ROMA_USER_1ST_PUBLIC_KEY="$ROMA_USER_1ST_PUBLIC_KEY" \
          --from-literal=ROMA_CONTROL_PASSPORT_PASSPORT="$ROMA_CONTROL_PASSPORT_PASSPORT" \
          --from-literal=ROMA_CONTROL_PASSPORT_PASSPORT_PUB="$ROMA_CONTROL_PASSPORT_PASSPORT_PUB" \
          --from-literal=ROMA_CONTROL_PASSPORT_PASSWORD="$ROMA_CONTROL_PASSPORT_PASSWORD" \
          --from-literal=ROMA_DATABASE_CDB_URL="$ROMA_DATABASE_CDB_URL" \
          --from-literal=ROMA_USER_1ST_NAME="$ROMA_USER_1ST_NAME" \
          --from-literal=ROMA_USER_1ST_NICKNAME="$ROMA_USER_1ST_NICKNAME" \
          --from-literal=ROMA_USER_1ST_ROLES="$ROMA_USER_1ST_ROLES" \
          --from-literal=ROMA_ENCRYPTION_KEY="$ROMA_ENCRYPTION_KEY" \
          --from-literal=ROMA_JWT_SECRET="$ROMA_JWT_SECRET" \
          -n demo --dry-run=client -o yaml | kubectl --kubeconfig=/drone/src/kubeconfig apply -f -

  - name: deploy to demo
    image: registry.cn-hongkong.aliyuncs.com/binrcbase/kubectl
    environment:
      KUBECONFIG:
        from_secret: kubeconfig_data
      HOME: /root
      IMAGE_TAG: ${DRONE_TAG}
      NAMESPACE: demo
    commands:
      - echo "$KUBECONFIG" > /drone/src/kubeconfig
      - |
        # 使用 demo 环境的专用配置文件，只替换镜像标签
        sed -e "s|registry.cn-hongkong.aliyuncs.com/binrchq/roma:latest|registry.cn-hongkong.aliyuncs.com/binrchq/roma:$IMAGE_TAG|g" \
            deployment/k8s-deployment-demo.yaml > /drone/src/k8s-deployment.demo.yaml
      - |
        # 验证关键配置
        if ! grep -q "name: roma-demo-backend" /drone/src/k8s-deployment.demo.yaml; then
          echo "ERROR: Deployment name should be roma-demo-backend"
          exit 1
        fi
        if ! grep -q "namespace: demo" /drone/src/k8s-deployment.demo.yaml; then
          echo "ERROR: Namespace should be demo"
          exit 1
        fi
        if ! grep -q "name: roma-demo-backend-service" /drone/src/k8s-deployment.demo.yaml; then
          echo "ERROR: Service name should be roma-demo-backend-service"
          exit 1
        fi
        if ! grep -q "app: roma-demo-backend" /drone/src/k8s-deployment.demo.yaml; then
          echo "ERROR: App label should be roma-demo-backend"
          exit 1
        fi
      - kubectl --kubeconfig=/drone/src/kubeconfig apply -f /drone/src/k8s-deployment.demo.yaml
      - kubectl --kubeconfig=/drone/src/kubeconfig rollout status deployment/roma-demo-backend -n $NAMESPACE --timeout=5m
