package constants

const (
	MySQL         = "MySQL"
	PostgreSQL    = "PostgreSQL"
	SQLite        = "SQLite"
	MSSQL         = "Microsoft SQL Server"
	Oracle        = "Oracle"
	MongoDB       = "MongoDB"
	Redis         = "Redis"
	Cassandra     = "Cassandra"
	Couchbase     = "Couchbase"
	DynamoDB      = "Amazon DynamoDB"
	MariaDB       = "MariaDB"
	SQLite3       = "SQLite3"
	MemSQL        = "MemSQL"
	Vertica       = "Vertica"
	Firebird      = "Firebird"
	CockroachDB   = "CockroachDB"
	Greenplum     = "Greenplum"
	ClickHouse    = "ClickHouse"
	ArangoDB      = "ArangoDB"
	Neo4j         = "Neo4j"
	OrientDB      = "OrientDB"
	Elasticsearch = "Elasticsearch"
	HBase         = "HBase"
	Bigtable      = "Bigtable"
	Teradata      = "Teradata"
	DB2           = "IBM DB2"
	Informix      = "Informix"
	Sybase        = "Sybase"
	VoltDB        = "VoltDB"
	Snowflake     = "Snowflake"
	Presto        = "Presto"
	YugabyteDB    = "YugabyteDB"
	TimescaleDB   = "TimescaleDB"
	InfluxDB      = "InfluxDB"
	TiDB          = "TiDB"
	ArangoSearch  = "ArangoSearch"
	FaunaDB       = "FaunaDB"
)
